### PR TITLE
Fixed issue with non member proteins being showed up

### PR DESCRIPTION
**Pull request by tanksha**
Filtered out proteins which are only in the same pathway with the gene.

---
This change is [Reviewable](https://reviewable.io/reviews/mozi-ai/annotation-scheme/16)

### CODE REVIEW

**Comment by tanksha** [comment]
@Habush 
- Why have the protein check at two different places? i.e I see (if (equal? prot "True")) at line 35 and 46
One is checked to retrieve the  member proteins of the pathways we are looping through
and the second it to return (Gene expresses protein) rather than (Gene Memberof Pathway) which only needs to be done if protein is selected, 
And they will not be done inside the let but will consider using the value inside let rather than calling the function again. 

- Why add an option argument when you can compare the pathway names to check which pathway it is? It looks unnecessary.
The findproteins functions is being called from both SMPDB and reactome functions and needs to have identifier

**Comment by tanksha** [comment]
@Habush I used ### string-contains to check if "complex" is in the name but as some compartments end with "ome", string-contain will not handle that as it has to end with it, not contains.

**Comment by Habush** [comment]
@tanksha I see. Then, `string-suffix?` is what you want. In your case you would do `(string-suffix"? ome membrane" loc)`. Please check it and let me know if it satisfies your requirement. You can find the documentation [here](https://srfi.schemers.org/srfi-13/srfi-13.html#PrefixesSuffixes)

**Comment by tanksha** [comment]
@Habush It seems not to be the one
scheme@(guile-user)> (string-suffix? "lysosome" "ome")
$5 = #f

**Comment by tanksha** [comment]
Never mind, the suffix need to be first. It works 
scheme@(guile-user)> (string-suffix? "ome" "lysosome")
$8 = #t

**Pull request merged**
