### PR TITLE
Remove the env.in file.

### PR DESCRIPTION
**Pull request by linas**
It serves no purpose here; this seems to be a cut-n-paste
error from the guile sources, which wanted to run guild from
the build directory. But we do not provide guild, so we don't
need this.

### CODE REVIEW

**Comment by rekado** [comment]
"env" can still be useful to put the files of the source directory on the load path first.  This may be needed for `make distcheck`, which runs in a sub-directory.

**Comment by linas** [comment]
Yes, it *could* be useful for several reasons. However, it isn't being used for anything, except incorrectly, to look for `guild`. And worse, it's buggy: it is appending `/opt` to search paths (at least on my computer) and that's just wrong. So ... its buggy, and its being used in one place .. incorrectly.  It needs to be ripped out.

As a general rule (there are always exceptions) .. as a general rule, git rid of everything that isn't needed. Unused stuff is hard to debug, hard to understand, confusing as to how important it is, and is a general time-waster during maintenance activities. And worse: clutter and lack of clarity prevent future work, future expansion. It makes it harder to understand how to add new features. 

(Anyway, `make distcheck` already works correctly in the automake system; you do not need anything extra like this to make it work.)

**Comment by rekado** [comment]
> And worse, it's buggy: it is appending /opt to search paths (at least on my computer) and that's just wrong. So ... its buggy, and its being used in one place .. incorrectly. It needs to be ripped out.

Yeah, that *is* wrong.  `env` should be generated from `env.in`, so at the very least `env` should be removed as it is a generated file.

(I agree with the general rule of not keeping stuff that isn't needed, aka YAGNI.)

The script is not used for finding `guild`.  It's used to make sure that the GUILE_LOAD_PATH and GUILE_LOAD_COMPILED_PATH are set to the source directory when compiling.  It doesn't make a difference in isolated build environments but is used to avoid loading sources and compiled Guile modules from locations that happen to be on the load path.

Using an `env` script like this is a common idiom in Guile packages, e.g. when running tests.  It is also used in `guile.am` in the default rule for compiling `.scm` to `.go`.

**Comment by linas** [comment]
To paraphrase the original star-wars movie -- "Read the code, Luke".  It was being used in one and only one place, and that was to find the `guild` compiler, which is pointless, because, for us, the `guild` compiler is always at a system install path, and never in our source path.  Also, if you don't know where `guild` is, you'd have to use `/usr/bin/env` to find it, and not this script.

**Comment by linas** [comment]
To be clear: the `guile.am` being used here was just-plain buggy.  It appears to have been a cut-n-paste error from the main `guile` repo, where having something like this makes sense, but in this project, it just generates nonsense.

**Comment by rekado** [comment]
Can you please show me how the `env` script "tries to find `guild`"?  It doesn't do that.  It sets the load path for source files to be compiled by `guild` and the load-compiled-path for already compiled modules.  This is nothing like `/usr/bin/env`.

I agree that `env` should be removed, because `env` ought to be generated from `env.in` so that the correct source directory is used.

(I have no stake in this, but as a Guiler I felt the need to correct what seems like a misunderstanding.)

**Comment by linas** [comment]
It's in the pull-req. Right here: `$(AM_V_GEN)$(top_builddir)/env $(GUILE_TOOLS)` 

*If its "nothing like `env`", then why is it called `env`? That's just a deeply and fundamentally misleading name.  There is an env, it's provided by `coreutils` on most distros, it's worked great for 30 or 40 years, and to introduce some rando file called `env` that is somehow different is lunatic, right up there with having executable files called `cp`, `cd` and so on. It's a gross violation of the principle of least surprise, bordering on  security vuln.

* If search paths need to be set, then why not set them in `Makefile.am`? If they need to be configured, why not configure them in `configure.ac`? 

I'm not misunderstanding this: its just a brain-damaged file that was just-plain buggy. Removing it actually lets the code build, and the unit tests to pass.

**Comment by rekado** [comment]
> It's in the pull-req. Right here: $(AM_V_GEN)$(top_builddir)/env $(GUILE_TOOLS)

This only means that `guild` is called in the environment set up by the "env" script, because "env" `exec`s its argument.

It's called "env" because it sets up the environment.  It's a conventional name.

> If they need to be configured, why not configure them in configure.ac?

Because the location is "volatile" and only valid during build. 

> I'm not misunderstanding this: its just a brain-damaged file that was just-plain buggy. Removing it actually lets the code build, and the unit tests to pass.

"env" is wrong, yes.  "env.in" is not.

**Comment by linas** [comment]
I seriously do not understand why you are arguing this. First,

* It breaks the build. It literally prevents the code from building and running correctly. Crash/error. Removing this allows the code to build and run and pass tests.
* If you look at the paths, there's nothing "volatile" about them. The path is literally assembled from paths that were set up in automake/configure: they are just as static as configure.
* The ONLY thing that this does is to invoke the guild compiler. But guild runs fine without that.  The paths that it sets up are not only bogus, but lead to faulty builds.

I mean, I've spent the last week trying to get this code to build and run. There are many serious problems in this code base -- stuff just crashes, passes bad arguments, spews endless warnings -- and one reason for this is that the code looks to be excessively over-complexitificationated.  The first step in such a situation is to remove all complexity that is not needed.  Reduce the total number of lines of code.  The easiest way to make something run more reliably is to not run it at all.  And that's the goal of this pull req.

**Comment by rekado** [comment]
> I seriously do not understand why you are arguing this.

I guess I can't express this any different.  That's okay.

> There are many serious problems in this code base -- stuff just crashes, passes bad arguments, spews endless warnings -- and one reason for this is that the code looks to be excessively over-complexitificationated

From a cursory look I agree with this assessment.  I just think there are hundreds of other places that would benefit from removal or rewrites --- and the conventional `env.in` just isn't one of them.

¯\_(ツ)_/¯

But as I wrote earlier: I have no stake in this and I think it's the right thing to remove the generated `env`.

**Comment by linas** [comment]
OK ... well. I wouldn't call it  "conventional"? -- I've hacked dozens of automake/autoconf projects; none have ever done anything like this before. Even if I look at, for example, the sources for guile itself, the only `env`'s it has are:
```
guile-git/m4/secure_getenv.m4
guile-git/m4/environ.m4
guile-git/m4/putenv.m4
guile-git/m4/setenv.m4
guile-git/meta/build-env.in
guile-git/meta/uninstalled-env.in
``` 
I can see how the last two could be useful: guile is boot-strapping itself during the build, and so it has to re-direct which compiler it's using, and both the source and the target directories. Fiddling with paths is common in any kind of cross-compiler devel or in self-hosting/bootstrapping devel. So gcc, llvm and glibc have these kinds of files as well. (And these build env's used to be notoriously difficult to set up correctly). 

But, in this case, we are neither cross-compiling nor self-hosting. All dependencies -- things like the guile site dir, and the guile go dir, are already populated with a bunch of other stuff needed for this particular project to build, and you're not going to be swapping those around, replacing them with some other dirs containing something else. Dependencies have already been installed in fixed, hard-coded locations.  The situation here is very very unlike boot-strapping builds.

**Comment by rekado** [comment]
"Conventional" not in generic autoconf/automake projects, true, but in Guile packages:

https://git.savannah.gnu.org/cgit/guile-opengl.git/tree/env.in
https://git.savannah.gnu.org/cgit/gwl.git/tree/env.in
https://notabug.org/cwebber/guile-gcrypt/src/master/pre-inst-env.in
https://github.com/aconchillo/guile-json/blob/master/env.in
https://git.savannah.nongnu.org/cgit/guile-debbugs.git/tree/env.in
https://gitlab.com/guile-git/guile-git/blob/master/pre-inst-env.in

This isn't to say that it is *required* here, just that it's not something terribly idiosyncratic in this project.

**Comment by linas** [comment]
Closing for now, in favor of pull req #92.  I have not yet tested #92, because testing is hard, due to the large number of work-arounds that I'm having to carry.

**Pull request closed without merging**
