### PR TITLE
Mutation be gone

### PR DESCRIPTION
**Pull request by rekado**
This is ongoing work to remove instances of mutation where possible.

### CODE REVIEW

**Comment by rekado** [comment]
(This branch is based on top of the simplify-parser branch.)

**Comment by rekado** [comment]
In commit https://github.com/MOZI-AI/annotation-scheme/pull/122/commits/40194a0cd1013398d027fd17bb106a1fb41172a0 when adding annotation/graph.scm I didn't know who authored the record definitions in the fork of Guile JSON.  This would need to be changed before merging.

**Comment by linas** [comment]
I skimmed this and it looks reasonable. When you say, "ongoing work", does that mean its not yet ready to merge?  Or can it be merged now?

It might have been easier to review & merge, if this was half-a-dozen distinct pull reqs, instead of one big one...

**Comment by linas** [comment]
Oh  and this comment: 
> (This branch is based on top of the simplify-parser branch.)

I assume you are referring to pull req #121 -- the duplicated changes here and there clutters the review here a bit. This is easily fixed by saying:
```
git checkout master
git pull
git checkout mutation-be-gone
git merge master
git push
```
which will make the already-merged changes disappear from this pull-req.

**Comment by rekado** [comment]
I rebased it onto master.

**Comment by rekado** [comment]
> When you say, "ongoing work", does that mean its not yet ready to merge? Or can it be merged now?

This could be merged now --- once it is confirmed that the semantics are actually preserved.  Most changes are very conservative, but in other places I wasn't 100% sure what the intended behaviour should be, e.g. when single branched `if`s were used without exhaustive patterns for all possible cases, etc.

"ongoing" just means that there's still some mutation and still some really odd-looking clunkers that need some more work.  One example is `find-go-term` with its terribly unidiomatic loop, or `reactome`, which sets a list inside of an `append-map`...

**Comment by rekado** [comment]
`gene-pathway-annotation` is another candidate for a rewrite in future commits.

**Comment by Habush** [comment]
@rekado about `find-go-term`, I wrote that code and looking at it now you are right, it is clunky. @linas suggested me a better way to do the traversal in this [issue](https://github.com/opencog/atomspace/issues/2472). I will make those changes soon

**Comment by linas** [comment]
Any progress on this? I'm interested in clearing out the backlog of suggested patches, etc. and it makes no sense to work on those until this one is merged.

**Pull request merged**
