### PR TITLE
Fix the issue of parser not handling a list of ListLinks

### LINKED ISSUE #162: annotate-genes returning empty list of nodes and edges.
After the latest improvements to the parser by @rekado, the `annotate-genes` function is returning empty list of nodes and edges. To reproduce this issue, load the `sample_dataset.scm` and run the annotation for `IGF1` as follows:

```
(annotate-genes (list "IGF1") "test-res"  "[{\"function_name\": \"gene-pathway-annotation\", \"filters\": [{\"filter\": \"pathway\", \"value\": \"smpdb reactome\"},{\"filter\": \"include_prot\", \"value\": \"True\"}, {\"filter\": \"include_sm\", \"value\": \"False\"},{\"filter\": \"coding\", \"value\": \"True\"},{\"filter\": \"noncoding\", \"value\": \"True\"}, {\"filter\": \"biogrid\", \"value\": \"0\"}]}, {\"function_name\": \"gene-go-annotation\", \"filters\": [{\"filter\": \"namespace\", \"value\": \"biological_process cellular_component molecular_function\"}, {\"filter\": \"parents\", \"value\": \"0\"}, {\"filter\": \"protein\", \"value\": \"True\"}]}, {\"function_name\": \"include-rna\", \"filters\": [{\"filter\": \"coding\", \"value\": \"True\"},{\"filter\": \"noncoding\", \"value\": \"True\"},{\"filter\": \"protein\", \"value\": \"1\"}]},{\"function_name\": \"biogrid-interaction-annotation\", \"filters\": [{\"filter\": \"interaction\", \"value\": \"Proteins\"}]}]")
```
The above returns the following json:

```
"{\"nodes\":{},\"edges\":{}}"
```

### PR DESCRIPTION
**Pull request by Habush**
This fixes #162. Note this PR is different from #171 as it still does string conversion. #171 still needs more work so this one is quick-fix till the other PR is merged.

### CODE REVIEW

**Comment by tanksha** [comment]
@Habush with this PR I am getting error at `annotate-genes` function, unable to convert the json to string, did you check?

**Comment by Habush** [comment]
Ah, yes. I forgot to mention this PR depends on the fixes done on https://github.com/aconchillo/guile-json/pull/54. Until the maintainer of the `guile-json` repo merges the PR, please use the forked repo and checkout the `json-string-fix` branch.

**Comment by linas** [comment]
Well, this is sort-of dangerous; anchillo might take a day or a week or months to apply the patch, or might reject it. In the meanwhile. the unit tests break... and I guess the system breaks too? Is there a way to work around this so that both forms work?

**Comment by rekado** [comment]
As I commented on the Guile JSON PR, I think this is the wrong approach.  Why not pre-process your data to convert records to one of the many possible string representations?

**Pull request merged**
