### PR TITLE
Use SetLink instead of ListLink for biogrid symmetric interactions

### PR DESCRIPTION
**Pull request by tanksha**

### CODE REVIEW

**Comment by linas** [comment]
look good to me .. are there matching updates to the dataset importers? (Where are those? in agi-bio or somewhere else?)

**Comment by tanksha** [comment]
@linas I have created a new repo for the import scripts https://github.com/MOZI-AI/knowledge-import ... as the MOZI-AI/agi-bio is a fork, I will delete it. what do you think if we have MOZI-AI/knowledge-import repo as a submodule for opencog/agi-bio so that my updates will be for both?

**Comment by linas** [comment]
MOZI-AI/knowledge-import  seems fine.  

I dislike submodules: in my experience, they are confusing, they create spurious diffs, and are hard to keep in sync (since they are designed to allow version skew ... which might be OK for some projects, but is terrible for others).  So, it would be best if you could remove everything in opencog/agi-bio that is in MOZI-AI/knowledge-import and alter the agi-bio-README to say that the MOZI project uses import scripts are in MOZI-AI/knowledge-import.

**Comment by linas** [comment]
Should probably remove opencog/agi-bio/knowledge-import/parse-owl too because I think that maybe MOZI.AI/owl2atomese is newer!? Or something like that? 

Also, maybe  MOZI.AI/owl2atomese should be merged into MOZI.AI/knowledge-import (maybe?)  it seems to be used for importing gene-ontology stuff, and so should probably live in the same git repo as the rest of the import code ...

**Pull request merged**
