### PR TITLE
Remove unused file

### PR DESCRIPTION
**Pull request by linas**

### CODE REVIEW

**Comment by tanksha** [comment]
@linas  Some tests failed without the dependency modules, so we have to use this file

**Comment by linas** [comment]
Please try pull req #80.  After this, the vast ocean of build-test failures suddenly disappeared for me. I was tearing my hair out trying to work out what was wrong... it turns out the test-harness file in `build-aux` was obsolete and at the root cause of all the nuttiness.

**Comment by linas** [comment]
anyway, after #80, all of the unit tests now pass. So its like magic:-)

**Comment by linas** [comment]
Uh, excuse me? You closed this without merging. Please re-open and merge!

**Comment by Habush** [comment]
@tanksha opencog_deps file should be moved to the python code as it isn't needed here.

**Comment by rekado** [comment]
The tests fail now because tests/main-tests.scm includes this file.

**Pull request merged**
