### PR TITLE
Remove unnecessary call/cc 

### PR DESCRIPTION
**Pull request by Habush**
Remove the call/cc which are unnecessary and according to @linas have impact on performance. This is discussed in #98

### CODE REVIEW

**Comment by linas** [comment]
Thank you; this seems to work. For me "to work" means "not to crash", and I can now get performance trace results as described in #98 I cannot tell if this is generating correct results or not.

**Comment by tanksha** [comment]
@Habush the GO cross annotation from biogrid is not working. Check running the biogrid-annotation with GO namespace and the interaction type being "Protein".  it doesn't have any GO result. Please include that.

**Comment by rekado** [comment]
Is there a test for this property of the parser result?  Having more extensive tests would allow for more confident refactoring of the parser code.

**Comment by Habush** [comment]
@rekado, @tanksha's issue isn't related to the parser specifically. It is related to issue #114. Hedra, please delete or edit the above comment

**Pull request merged**
